


CREATE TABLE `CUSTOMERS` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` VARCHAR(26),
  `GENDER` VARCHAR(26),
  `AGE` INT,
  `HOME_ADDRESS` VARCHAR(128),
  `ZIP_CODE` INT,
  `CITY` VARCHAR(26),
  `STATE` VARCHAR(128),
  `COUNTRY` VARCHAR(26),
  `DATE_NAISSANCE` DATE,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_TYPE` VARCHAR(26),
  `PRODUCT_NAME` VARCHAR(26),
  `PRODUCT_SIZE` VARCHAR(26),
  `COLOUR` VARCHAR(26),
  `PRICE` DECIMAL(10,2),
  `QUANTITY` INT,
  `DESCRIPTION` VARCHAR(128),
  PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ORDERS` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `PAYMENT` DECIMAL(10,2),
  `ORDER_DATE` DATE,
  `DELIVERY_DATE` DATE,
  PRIMARY KEY (`ORDER_ID`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMERS` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `SALES` (
  `SALES_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `PRICE_PER_UNIT` DECIMAL(10,2),
  `QUANTITY` INT,
  `TOTAL_PRICE` DECIMAL(10,2),
  PRIMARY KEY (`SALES_ID`),
  FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ORDER_ID`),
  FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
