CREATE TABLE weather_data (
    data_id INT NOT NULL AUTO_INCREMENT,
    date DATE NOT NULL,
    weather_condition VARCHAR(50),
    traffic_intensity VARCHAR(50),
    MinTemp FLOAT,
    MaxTemp FLOAT,
    Rainfall FLOAT,
    Evaporation FLOAT,
    Sunshine FLOAT,
    WindGustDir VARCHAR(10),
    WindGustSpeed FLOAT,
    WindDir9am VARCHAR(10),
    WindDir3pm VARCHAR(10),
    WindSpeed9am FLOAT,
    WindSpeed3pm FLOAT,
    Humidity9am FLOAT,
    Humidity3pm FLOAT,
    Pressure9am FLOAT,
    Pressure3pm FLOAT,
    Cloud9am FLOAT,
    Cloud3pm FLOAT,
    Temp9am FLOAT,
    Temp3pm FLOAT,
    RainToday VARCHAR(5),
    RISK_MM FLOAT,
    RainTomorrow VARCHAR(5),
    PRIMARY KEY (data_id)
);
